// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using flo.desarrollo.prueba.datos;

namespace flo.desarrollo.prueba.datos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210830001344_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("flo.desarrollo.prueba.entidades.Articulo.Articulo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.ToTable("Articulo");
                });

            modelBuilder.Entity("flo.desarrollo.prueba.entidades.Fabricante.Fabricante", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArticuloCodigo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.HasIndex("ArticuloCodigo");

                    b.ToTable("Fabricante");
                });

            modelBuilder.Entity("flo.desarrollo.prueba.entidades.Fabricante.Fabricante", b =>
                {
                    b.HasOne("flo.desarrollo.prueba.entidades.Articulo.Articulo", null)
                        .WithMany("Fabricante")
                        .HasForeignKey("ArticuloCodigo");
                });

            modelBuilder.Entity("flo.desarrollo.prueba.entidades.Articulo.Articulo", b =>
                {
                    b.Navigation("Fabricante");
                });
#pragma warning restore 612, 618
        }
    }
}
